services:
    knp.rad.user.event_listener.password_hash_listener:
        class: Knp\Rad\User\EventListener\PasswordHashListener
        public: false
        arguments:
            - @security.encoder_factory
        tags:
            - { name: doctrine.event_listener, event: preUpdate, method: preUpdate }
            - { name: doctrine.event_listener, event: prePersist, method: prePersist, priority: 100 }

    knp.rad.user.event_listener.salt_generation_listener:
        class: Knp\Rad\User\EventListener\SaltGenerationListener
        public: false
        tags:
            - { name: doctrine.event_listener, event: prePersist, method: prePersist, priority: 200 }
